INCDIR = -I segment -I../ `pkg-config --cflags opencv`
OPT    = -O3
CPP    = g++
CFLAGS = $(DBG) $(OPT) $(INCDIR) -std=c++11
LINK   = -lm `pkg-config --libs opencv`

all: segment_opencv.o test

segment_opencv.o: segment_opencv.cpp segment_opencv.h
	$(CPP) $(CFLAGS) -c $< -o $@

test: test.cpp segment_opencv.o
	$(CPP) $(CFLAGS) -o $@ $^ $(LINK)

clean:
	/bin/rm -f segment_opencv.o test

clear: clean

